// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"iwut-app-center/internal/adapter/auth"
	"iwut-app-center/internal/adapter/generator"
	"iwut-app-center/internal/adapter/mongo"
	"iwut-app-center/internal/adapter/transport"
	"iwut-app-center/internal/application/usecase"
	"iwut-app-center/internal/config"
	usecase2 "iwut-app-center/internal/version/usecase"
)

// Injectors from wire.go:

// wireApp is the composition root injector. Generate wire_gen.go with:
//
//	wire gen ./cmd/app-center
//
// Do not hand-edit the generated file.
func wireApp(configuration config.Config) (*kratos.App, func(), error) {
	serverConfig := provideServerConfig(configuration)
	systemClock := generator.NewSystemClock()
	identityConfig, err := provideIdentityConfig(configuration, systemClock)
	if err != nil {
		return nil, nil, err
	}
	identityVerifier, err := transport.NewIdentityVerifier(identityConfig)
	if err != nil {
		return nil, nil, err
	}
	uuiDv7Generator := generator.NewUUIDv7Generator()
	client, cleanup, err := provideMongoClient(configuration)
	if err != nil {
		return nil, nil, err
	}
	database, err := provideMongoDatabase(client, configuration)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	applicationRepository := mongo.NewApplicationRepository(database)
	int32_2 := provideInitialApplicationQuota(configuration)
	createApplicationHandler := usecase.NewCreateApplicationHandler(uuiDv7Generator, systemClock, applicationRepository, int32_2)
	applicationService := transport.NewApplicationService(createApplicationHandler)
	clientConn, cleanup2, err := provideAuthScopeCatalogConnection(configuration)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcScopeCatalogSnapshotSource, err := auth.NewGRPCScopeCatalogSnapshotSource(clientConn)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	duration := provideScopeCatalogCacheTTL(configuration)
	scopeCatalogCache, err := auth.NewScopeCatalogCache(grpcScopeCatalogSnapshotSource, systemClock, duration)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	applicationVersionUUIDv7Generator := generator.NewApplicationVersionUUIDv7Generator()
	applicationVersionRepository := mongo.NewApplicationVersionRepository(database)
	createApplicationVersionHandler := usecase2.NewCreateApplicationVersionHandler(scopeCatalogCache, applicationVersionUUIDv7Generator, systemClock, applicationVersionRepository)
	updateDraftApplicationVersionHandler := usecase2.NewUpdateDraftApplicationVersionHandler(scopeCatalogCache, systemClock, applicationVersionRepository)
	applicationVersionService := transport.NewApplicationVersionService(createApplicationVersionHandler, updateDraftApplicationVersionHandler)
	servers, err := transport.NewServers(serverConfig, identityVerifier, applicationService, applicationVersionService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := provideApp(servers)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
