// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"iwut-app-center/internal/adapter/auth"
	"iwut-app-center/internal/adapter/generator"
	"iwut-app-center/internal/adapter/mongo"
	"iwut-app-center/internal/adapter/oauthcredential"
	"iwut-app-center/internal/adapter/preflight"
	"iwut-app-center/internal/adapter/testercredential"
	"iwut-app-center/internal/adapter/transport"
	"iwut-app-center/internal/application/usecase"
	usecase6 "iwut-app-center/internal/catalog/usecase"
	"iwut-app-center/internal/config"
	usecase8 "iwut-app-center/internal/oauthclient/usecase"
	usecase7 "iwut-app-center/internal/profile/usecase"
	usecase4 "iwut-app-center/internal/publication/usecase"
	usecase3 "iwut-app-center/internal/review/usecase"
	usecase5 "iwut-app-center/internal/tester/usecase"
	usecase2 "iwut-app-center/internal/version/usecase"
)

// Injectors from wire.go:

// wireApp is the composition root injector. Generate wire_gen.go with:
//
//	wire gen ./cmd/app-center
//
// Do not hand-edit the generated file.
func wireAppWithResolver(configuration config.Config, resolver preflight.Resolver) (*kratos.App, func(), error) {
	serverConfig := provideServerConfig(configuration)
	systemClock := generator.NewSystemClock()
	identityConfig, err := provideIdentityConfig(configuration, systemClock)
	if err != nil {
		return nil, nil, err
	}
	identityVerifier, err := transport.NewIdentityVerifier(identityConfig)
	if err != nil {
		return nil, nil, err
	}
	uuiDv7Generator := generator.NewUUIDv7Generator()
	client, cleanup, err := provideMongoClient(configuration)
	if err != nil {
		return nil, nil, err
	}
	database, err := provideMongoDatabase(client, configuration)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	applicationRepository := mongo.NewApplicationRepository(database)
	int32_2 := provideInitialApplicationQuota(configuration)
	createApplicationHandler := usecase.NewCreateApplicationHandler(uuiDv7Generator, systemClock, applicationRepository, int32_2)
	applicationService := transport.NewApplicationService(createApplicationHandler)
	serviceIdentitySigner, err := provideServiceIdentitySigner(configuration, systemClock)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	clientConn, cleanup2, err := provideAuthScopeCatalogConnection(configuration, serviceIdentitySigner)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcScopeCatalogSnapshotSource, err := auth.NewGRPCScopeCatalogSnapshotSource(clientConn)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	duration := provideScopeCatalogCacheTTL(configuration)
	scopeCatalogCache, err := auth.NewScopeCatalogCache(grpcScopeCatalogSnapshotSource, systemClock, duration)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	oAuthRedirectPolicy := preflight.NewOAuthRedirectPolicy()
	applicationVersionUUIDv7Generator := generator.NewApplicationVersionUUIDv7Generator()
	applicationVersionRepository := mongo.NewApplicationVersionRepository(database)
	createApplicationVersionHandler := usecase2.NewCreateApplicationVersionHandler(scopeCatalogCache, oAuthRedirectPolicy, applicationVersionUUIDv7Generator, systemClock, applicationVersionRepository)
	updateDraftApplicationVersionHandler := usecase2.NewUpdateDraftApplicationVersionHandler(scopeCatalogCache, oAuthRedirectPolicy, systemClock, applicationVersionRepository)
	applicationVersionService := transport.NewApplicationVersionService(createApplicationVersionHandler, updateDraftApplicationVersionHandler)
	reviewScopeCatalog := auth.NewReviewScopeCatalog(scopeCatalogCache)
	launchURLSubmissionPolicy := preflight.NewLaunchURLSubmissionPolicy(resolver)
	applicationReviewUUIDv7Generator := generator.NewApplicationReviewUUIDv7Generator()
	applicationReviewRepository := mongo.NewApplicationReviewRepository(database)
	submitApplicationVersionReviewHandler := usecase3.NewSubmitApplicationVersionReviewHandler(reviewScopeCatalog, launchURLSubmissionPolicy, oAuthRedirectPolicy, applicationReviewUUIDv7Generator, systemClock, applicationReviewRepository)
	applicationReviewRestorationRepository := mongo.NewApplicationReviewRestorationRepository(database)
	restoreRejectedApplicationVersionHandler := usecase3.NewRestoreRejectedApplicationVersionHandler(systemClock, applicationReviewRestorationRepository)
	versionReviewPolicyRepository := mongo.NewVersionReviewPolicyRepository(database)
	grpcDeveloperSuspensionChecker, err := auth.NewGRPCDeveloperSuspensionChecker(clientConn)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	applicationReviewDecisionRepository := mongo.NewApplicationReviewDecisionRepository(database)
	grpcSystemPrincipalResolver, err := auth.NewGRPCSystemPrincipalResolver(clientConn)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	decideApplicationVersionReviewHandler := usecase3.NewDecideApplicationVersionReviewHandler(versionReviewPolicyRepository, grpcDeveloperSuspensionChecker, reviewScopeCatalog, launchURLSubmissionPolicy, oAuthRedirectPolicy, systemClock, applicationReviewDecisionRepository, grpcSystemPrincipalResolver)
	applicationReviewService := transport.NewApplicationReviewService(submitApplicationVersionReviewHandler, restoreRejectedApplicationVersionHandler, decideApplicationVersionReviewHandler)
	publicationScopeCatalog := auth.NewPublicationScopeCatalog(scopeCatalogCache)
	publicationLaunchURLSubmissionPolicy := preflight.NewPublicationLaunchURLSubmissionPolicy(launchURLSubmissionPolicy)
	publicationUUIDv7Generator := generator.NewPublicationUUIDv7Generator()
	applicationPublicationRepository := mongo.NewApplicationPublicationRepository(database)
	placeApprovedVersionInTestSlotHandler := usecase4.NewPlaceApprovedVersionInTestSlotHandler(publicationScopeCatalog, publicationLaunchURLSubmissionPolicy, publicationUUIDv7Generator, systemClock, applicationPublicationRepository)
	setApprovedVersionInStableSlotHandler := usecase4.NewSetApprovedVersionInStableSlotHandler(publicationScopeCatalog, publicationLaunchURLSubmissionPolicy, publicationUUIDv7Generator, systemClock, applicationPublicationRepository)
	clearStableSlotHandler := usecase4.NewClearStableSlotHandler(publicationUUIDv7Generator, systemClock, applicationPublicationRepository)
	greyCohortSeedGenerator := generator.NewGreyCohortSeedGenerator()
	setGreyRolloutHandler := usecase4.NewSetGreyRolloutHandler(publicationScopeCatalog, publicationLaunchURLSubmissionPolicy, publicationUUIDv7Generator, greyCohortSeedGenerator, systemClock, applicationPublicationRepository)
	clearGreyRolloutHandler := usecase4.NewClearGreyRolloutHandler(publicationUUIDv7Generator, systemClock, applicationPublicationRepository)
	applicationPublicationService := transport.NewApplicationPublicationServiceWithGrey(placeApprovedVersionInTestSlotHandler, setApprovedVersionInStableSlotHandler, clearStableSlotHandler, setGreyRolloutHandler, clearGreyRolloutHandler)
	secureTesterJoinTokenFactory := testercredential.NewSecureTesterJoinTokenFactory()
	string2 := provideTesterJoinURLPrefix(configuration)
	testerJoinURLBuilder, err := testercredential.NewTesterJoinURLBuilder(string2)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	applicationTesterJoinLinkRepository := mongo.NewApplicationTesterJoinLinkRepository(database)
	createOrRotateTesterJoinLinkHandler := usecase5.NewCreateOrRotateTesterJoinLinkHandler(secureTesterJoinTokenFactory, testerJoinURLBuilder, publicationUUIDv7Generator, systemClock, applicationTesterJoinLinkRepository)
	revokeTesterJoinLinkHandler := usecase5.NewRevokeTesterJoinLinkHandler(systemClock, applicationTesterJoinLinkRepository)
	testerJoinLinkService := transport.NewTesterJoinLinkService(createOrRotateTesterJoinLinkHandler, revokeTesterJoinLinkHandler)
	tokenHasher := testercredential.NewTokenHasher()
	applicationTesterMembershipRepository := mongo.NewApplicationTesterMembershipRepository(database)
	joinApplicationAsTesterHandler := usecase5.NewJoinApplicationAsTesterHandler(tokenHasher, publicationUUIDv7Generator, systemClock, applicationTesterMembershipRepository)
	removeApplicationTesterHandler := usecase5.NewRemoveApplicationTesterHandler(systemClock, applicationTesterMembershipRepository)
	testerMembershipService := transport.NewTesterMembershipService(joinApplicationAsTesterHandler, removeApplicationTesterHandler)
	testLaunchResolver := mongo.NewTestLaunchResolver(database)
	resolveTestLaunchTarget := usecase6.NewResolveTestLaunchTarget(testLaunchResolver)
	catalogService := transport.NewCatalogService(resolveTestLaunchTarget)
	applicationProfileRevisionUUIDv7Generator := generator.NewApplicationProfileRevisionUUIDv7Generator()
	applicationProfileRevisionRepository := mongo.NewApplicationProfileRevisionRepository(database)
	createApplicationProfileRevisionHandler := usecase7.NewCreateApplicationProfileRevisionHandler(applicationProfileRevisionUUIDv7Generator, systemClock, applicationProfileRevisionRepository)
	updateDraftApplicationProfileRevisionHandler := usecase7.NewUpdateDraftApplicationProfileRevisionHandler(systemClock, applicationProfileRevisionRepository)
	applicationProfileRevisionService := transport.NewApplicationProfileRevisionService(createApplicationProfileRevisionHandler, updateDraftApplicationProfileRevisionHandler)
	applicationProfileReviewUUIDv7Generator := generator.NewApplicationProfileReviewUUIDv7Generator()
	submitApplicationProfileRevisionReviewHandler := usecase7.NewSubmitApplicationProfileRevisionReviewHandler(applicationProfileReviewUUIDv7Generator, systemClock, applicationProfileRevisionRepository)
	decideApplicationProfileRevisionReviewHandler := usecase7.NewDecideApplicationProfileRevisionReviewHandler(systemClock, applicationProfileRevisionRepository)
	applicationProfileReviewService := transport.NewApplicationProfileReviewService(submitApplicationProfileRevisionReviewHandler, decideApplicationProfileRevisionReviewHandler)
	oAuthClientUUIDv4Generator := generator.NewOAuthClientUUIDv4Generator()
	secretFactory := oauthcredential.NewSecretFactory()
	oAuthClientRepository := mongo.NewOAuthClientRepository(database)
	handlers := usecase8.NewHandlers(oAuthClientUUIDv4Generator, secretFactory, systemClock, oAuthClientRepository)
	oAuthClientService := transport.NewOAuthClientService(handlers)
	serviceIdentityConfig := provideServiceIdentityConfig(configuration)
	serviceIdentityVerifier, err := provideServiceIdentityVerifier(serviceIdentityConfig, systemClock)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	oAuthProviderRepository := mongo.NewOAuthProviderRepository(database, secretFactory)
	providerHandlers := usecase8.NewProviderHandlers(systemClock, oAuthProviderRepository)
	oAuthClientProviderService := transport.NewOAuthClientProviderService(providerHandlers)
	servers, err := transport.NewServersWithOAuthProvider(serverConfig, identityVerifier, applicationService, applicationVersionService, applicationReviewService, applicationPublicationService, testerJoinLinkService, testerMembershipService, catalogService, applicationProfileRevisionService, applicationProfileReviewService, oAuthClientService, serviceIdentityVerifier, oAuthClientProviderService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := provideApp(servers)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
