// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"iwut-app-center/internal/biz"
	"iwut-app-center/internal/conf"
	"iwut-app-center/internal/data"
	"iwut-app-center/internal/middleware"
	"iwut-app-center/internal/server"
	"iwut-app-center/internal/service"
	"iwut-app-center/internal/util"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	appRepo := data.NewAppRepo(dataData, confData, logger)
	appUsecase := biz.NewAppUsecase(appRepo)
	appService := service.NewAppService(appUsecase)
	jwtUtil := util.NewJwtUtil()
	jwtInfoMiddleware := middleware.NewJwtInfoMiddleware(jwtUtil)
	grpcServer := server.NewGRPCServer(confServer, appService, jwtInfoMiddleware, logger)
	httpServer := server.NewHTTPServer(confServer, appService, jwtInfoMiddleware, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
