// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"iwut-app-center/internal/biz"
	"iwut-app-center/internal/conf"
	"iwut-app-center/internal/data"
	"iwut-app-center/internal/middleware"
	"iwut-app-center/internal/server"
	"iwut-app-center/internal/service"
	"iwut-app-center/internal/util"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confService *conf.Service, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	appRepo := data.NewAppRepo(dataData, confData, logger)
	appVersionRepo := data.NewAppVersionRepo(dataData, confData, logger)
	authCenterUtil, cleanup2, err := util.NewAuthCenterUtil(confService, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	configCenterUtil := util.NewConfigCenterUtil(confService, logger)
	ruleParser := util.NewRuleParser(configCenterUtil)
	greyCalc := util.NewGreyCalc()
	appUsecase := biz.NewAppUsecase(appRepo, appVersionRepo, authCenterUtil, ruleParser, greyCalc, logger)
	jwtUtil := util.NewJwtUtil()
	appService := service.NewAppService(appUsecase, jwtUtil)
	appVersionUsecase := biz.NewAppVersionUsecase(appVersionRepo, appRepo, configCenterUtil, greyCalc, logger)
	appVersionService := service.NewAppVersionService(appVersionUsecase, jwtUtil)
	testerRepo := data.NewTesterRepo(dataData, confData, logger)
	testerUsecase := biz.NewTesterUsecase(testerRepo, appRepo, appVersionRepo, confServer, logger)
	testerService := service.NewTesterService(testerUsecase, jwtUtil)
	jwtInfoMiddleware := middleware.NewJwtInfoMiddleware(jwtUtil)
	grpcServer := server.NewGRPCServer(confServer, appService, appVersionService, testerService, jwtInfoMiddleware, logger)
	httpServer := server.NewHTTPServer(confServer, appService, appVersionService, testerService, jwtInfoMiddleware, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
